version: "3.9"

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "webdb"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    expose:
      - 5432
    ports:
      - "6432:5432"
    networks:
      - "backend"

  app:
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "webdb"
    build: app
    expose:
      - 8080
    ports:
      - "8080:80"
    networks:
      - "backend"
    depends_on:
      - postgres

networks:
  backend:
    name: backend
