version: "3.9"

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGDATA
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    expose:
      - 5432
    ports:
      - "6432:5432"
    networks:
      - "backend"

  app:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
    build: app
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - "backend"
    depends_on:
      - postgres

networks:
  backend:
    name: backend
