#!/bin/bash

show_usage() {
	cat <<-EOF
		Usage: $1 <command> <login> <password>

		Commands:
			sign-up      register the user using given login and password into database
			sign-in      authentificate the user using given login and password into database
	EOF
}

sign_up() {
	local login=$1
	local password=$2
	local json_request='{"usr":"'$login'","pwd":"'$password'"}'
	echo "HTTP: Request" $json_request
	curl -X POST http://localhost:8080/sign-up -H 'Content-Type: application/json' -d $json_request
}

sign_in() {
	local login=$1
	local password=$2
	local json_request='{"usr":"'$login'","pwd":"'$password'"}'
	echo "HTTP: Request" $json_request
	curl -X POST http://localhost:8080/auth -H 'Content-Type: application/json' -d $json_request
}

if [[ $# != 3 ]]; then
	show_usage $0
	exit 1
fi

cmd=$1
login=$2
password=$3
case $cmd in
sign-in)
	sign_in $login $password
	;;
sign-up)
	sign_up $login $password
	;;
*)
	show_usage $0
	;;
esac
